name: First Workflow
on: [push,workflow_dispatch]
jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: echo 'Devansh Popli'
      - name: Multiple commands
        run: |
            echo "Line1"
            echo "Line2"